#!/bin/bash

# Set the directory where the backgrounds are stored
BACKGROUND_DIR="$HOME/.config/backgrounds"
CURRENT_BACKGROUND_FILE="$HOME/.config/hypr/env/.current_background"

# Get the list of backgrounds
BACKGROUND_LIST=("$BACKGROUND_DIR"/*)
echo "Background list: ${BACKGROUND_LIST[@]}"

# Check if the current background file exists, otherwise set a default
if [[ -f "$CURRENT_BACKGROUND_FILE" ]]; then
    CURRENT_BACKGROUND=$(cat "$CURRENT_BACKGROUND_FILE")
else
    # Set the first background as the default if no current background is set
    CURRENT_BACKGROUND="${BACKGROUND_LIST[0]}"
    echo "$CURRENT_BACKGROUND" > "$CURRENT_BACKGROUND_FILE"
fi
echo "Current background: $CURRENT_BACKGROUND"

# Find the index of the current background in the list
CURRENT_INDEX=0
for i in "${!BACKGROUND_LIST[@]}"; do
    if [[ "${BACKGROUND_LIST[$i]}" == "$CURRENT_BACKGROUND" ]]; then
        CURRENT_INDEX=$i
        echo "Current index: $CURRENT_INDEX"
        break
    fi
done

# Calculate the index of the next background
NEXT_INDEX=$(( (CURRENT_INDEX + 1) % ${#BACKGROUND_LIST[@]} ))
echo "Next index: $NEXT_INDEX"

# Get the path of the next background
NEXT_BACKGROUND="${BACKGROUND_LIST[$NEXT_INDEX]}"
echo "Next background: $NEXT_BACKGROUND"

# Set the background to the next background
swww img $NEXT_BACKGROUND --transition-type grow --transition-fps 120 --transition-pos 'top-right' --transition-duration 2

# Save the current background in the file for persistence
echo "$NEXT_BACKGROUND" > "$CURRENT_BACKGROUND_FILE"

# Send a notification with the new background name and an icon from the current background
notify-send -i $NEXT_BACKGROUND "Background changed" "$(basename $NEXT_BACKGROUND)"
