#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
