#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## launch wofi with alt config

CONFIG="$HOME/.config/wofi/config"
STYLE="$HOME/.config/wofi/style.css"

if [[ ! `pidof wofi` ]]; then
	wofi -I --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE}
else
	pkill wofi
fi
